name: Salesforce CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Salesforce CLI
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
          tar xJf sfdx-linux-amd64.tar.xz
          ./sfdx/install
          echo "$(pwd)/sfdx/bin" >> $GITHUB_PATH

      - name: Authenticate Dev Hub
        run: sfdx auth:jwt:grant --clientid ${{ secrets.CONSUMER_KEY }} --jwtkeyfile assets/server.key --username ${{ secrets.SF_USERNAME }} --setdefaultdevhubusername -a DevHub

      - name: Create Scratch Org
        run: sfdx force:org:create -f config/project-scratch-def.json -a ScratchOrg -s -d 7

      - name: Push Source to Scratch Org
        run: sfdx force:source:push

      - name: Run Apex Tests
        run: sfdx force:apex:test:run --resultformat human --wait 10

      - name: Delete Scratch Org
        run: sfdx force:org:delete -u ScratchOrg -p
